### ISSUE TITLE
the position of the circle is offset when generating a two-level figure

### ISSUE THREAD

**Issue by rawenlei** [elmotec/circlify#1]
- hi:
- first thank you for your package circlify. i can draw beautiful circles without university mathematics knowledge.
- but during generating two-level figure, center of the circle were offset.
please check the following pictures and the code.
i am glad you for fixing the issue. and thank you again.
sorry, i cannot fix the code with MarkDown style.

best regards,
Rawen
rawen0623@live.com

![outimage](https://user-images.githubusercontent.com/42257971/56493591-2e348c80-6522-11e9-8699-f9701497bfc9.jpg)
def drawMutliCircle():
    a0=[0.8,0.2,0.1,0.05,0.05]
    a1=[0.3,0.2,0.2,0.1]
    a2=[0.1,0.05,0.05]
    a3=[0.05,0.04,0.01]
    l0=circ.circlify(a0,target_enclosure=circ.Circle(0,0,2048/1152-0.1),with_enclosure=True)
    l1=circ.circlify(a1,target_enclosure=circ.Circle(l0[0][0],l0[0][1],l0[0][2]),with_enclosure=True)
    l2=circ.circlify(a2,target_enclosure=circ.Circle(l0[1][0],l0[1][1],l0[1][2]),with_enclosure=True)
    l3=circ.circlify(a3,target_enclosure=circ.Circle(l0[2][0],l0[2][1],l0[2][2]),with_enclosure=True)
    fig,ax=plt.subplots(figsize=(6,6))
    l=l0+l1+l2+l3
    colors = [plt.cm.Dark2(i / len(l)) for i in range(len(l))]
    for j in l:
        c=Circle((j[0],j[1]),j[2],alpha=0.3,color=colors[l.index(j)-1])
        ax.add_patch(c)
        ax.plot()
    plt.show()

**Comment by rawenlei** [comment]
update:
l0=circ.circlify(a0,target_enclosure=circ.Circle(0,0,2048/1152-0.1),with_enclosure=True)
2048/1152 is my computer display resolution.i find adjust it can fix some circles.

**Comment by elmotec** [comment]
Hey @rawenlei,

Thank you for taking the time to bring up this issue. 

I am fixing the issue now. It should work in the next release and setting the target_enclosure with `Circle(0, 0, 2048/1152)` is just a happy coincidence that partially works around the problem.

**Comment by elmotec** [comment]
I believe the issue is fixed by f68f69d. Could you give [0.9.2](https://pypi.org/project/circlify/0.9.2/) a try when you get a chance and let me know if that's not the case?

**Comment by elmotec** [comment]
Here is what I am getting now with this code:
```
def drawMutliCircle():
    a0=[0.8,0.2,0.1,0.05,0.05]
    a1=[0.3,0.2,0.2,0.1]
    a2=[0.1,0.05,0.05]
    a3=[0.05,0.04,0.01]
    l0=circ.circlify(a0,with_enclosure=True)
    l1=circ.circlify(a1,target_enclosure=circ.Circle(*l0[0]),with_enclosure=True)
    l2=circ.circlify(a2,target_enclosure=circ.Circle(*l0[1]),with_enclosure=True)
    l3=circ.circlify(a3,target_enclosure=circ.Circle(*l0[2]),with_enclosure=True)
    fig, ax = plt.subplots(figsize=(6,6))
    l=l0+l1+l2+l3
    colors = [plt.cm.Dark2(i / len(l)) for i in range(len(l))]
    for j in l:
        c=plt.Circle((j[0],j[1]),j[2],alpha=0.3,color=colors[l.index(j)-1])
        ax.add_patch(c)
    ax.plot()
    plt.show()
```
![rawenlei](https://user-images.githubusercontent.com/1107551/56851225-85e44680-68da-11e9-8d83-4b1a9f42bb1b.png)

**Comment by rawenlei** [comment]
Hey @elmotec ,at first thank you very much!'
with the help of your circlify package, i can easily show the data visualization of circle packing by python.
please allow me to introduce the 'circlify' package which has the advantage of  quick response and small footprint to others programmer.
the following is the display of circle packing with three-levels deep via your 'circlify' package.

![image](https://user-images.githubusercontent.com/42257971/56874902-b6a9b480-6a6f-11e9-8e8c-a3af1c1d88a7.png)

**Comment by rraadd88** [comment]
> Here is what I am getting now with this code:
> 
> ```
> def drawMutliCircle():
>     a0=[0.8,0.2,0.1,0.05,0.05]
>     a1=[0.3,0.2,0.2,0.1]
>     a2=[0.1,0.05,0.05]
>     a3=[0.05,0.04,0.01]
>     l0=circ.circlify(a0,with_enclosure=True)
>     l1=circ.circlify(a1,target_enclosure=circ.Circle(*l0[0]),with_enclosure=True)
>     l2=circ.circlify(a2,target_enclosure=circ.Circle(*l0[1]),with_enclosure=True)
>     l3=circ.circlify(a3,target_enclosure=circ.Circle(*l0[2]),with_enclosure=True)
>     fig, ax = plt.subplots(figsize=(6,6))
>     l=l0+l1+l2+l3
>     colors = [plt.cm.Dark2(i / len(l)) for i in range(len(l))]
>     for j in l:
>         c=plt.Circle((j[0],j[1]),j[2],alpha=0.3,color=colors[l.index(j)-1])
>         ax.add_patch(c)
>     ax.plot()
>     plt.show()
> ```
> 
> ![rawenlei](https://user-images.githubusercontent.com/1107551/56851225-85e44680-68da-11e9-8d83-4b1a9f42bb1b.png)

Hi, @elmotec, its a great package. Using it, I would like to make a similar plot. However, in the latest version `0.10.0`,
I got this error 
```
TypeError: circlify() got an unexpected keyword argument 'with_enclosure'
```
The input parameters of `circ` are 
```
circ.circlify(data, target_enclosure=None, show_enclosure=False, datum_field='datum', id_field='id', children_field='children')
```
How could I make this plot in the latest version, or should I down-grade the package to earlier version. Please let me know.

**Comment by elmotec** [comment]
Did you try to use show_enclosure=True instead of with_enclosure=True? I believe I changed the parameter name in version 0.10.

**Comment by abubelinha** [comment]
I tried to run the above pieces of code and got indeed this error:
`NameError: name 'plt' is not defined`

I figure out I should add this at the top:
```Python
import matplotlib.pyplot as plt
import circlify as circ
```
But now when running the code I get:
> `c=plt.Circle((j[0],j[1]),j[2],alpha=0.3,color=colors[l.index(j)-1])`
> TypeError: 'Circle' object is not subscriptable

Could anyone tell me what I am doing wrong?
```
Windows 7
Python 3.8
circlify 0.15.0
matplotlib 3.6.3 
```
Thanks !!

**Comment by rawenlei** [comment]
Hi
plt is matplotlib’s abbr.
you can import it as:
import matplotlib.pyplot as plt


发件人: abubelinha ***@***.***>
发送时间: 2023年1月30日 3:59
收件人: elmotec/circlify ***@***.***>
抄送: rawenlei ***@***.***>; State change ***@***.***>
主题: Re: [elmotec/circlify] the position of the circle is offset when generating a two-level figure (#1)


Could anyone tell me where does plt object come from in the above pieces of code?
I tried to run them and I get indeed this error:

NameError: name 'plt' is not defined

Thanks

**Comment by abubelinha** [comment]
Thanks @rawenlei 
I edited my question and updated the code to import matplotlib and circlify. 
But a new error message appears a few lines below:
> `c=plt.Circle((j[0],j[1]),j[2],alpha=0.3,color=colors[l.index(j)-1])`
> TypeError: 'Circle' object is not subscriptable

**Comment by elmotec** [comment]
Thanks @rawenlei for the hand.  @abubelinha, could you try this? 

```python
import circlify as circ
import matplotlib.pyplot as plt

def drawMutliCircle():
    a0=[0.8,0.2,0.1,0.05,0.05]
    a1=[0.3,0.2,0.2,0.1]
    a2=[0.1,0.05,0.05]
    a3=[0.05,0.04,0.01]
    l0=circ.circlify(a0,with_enclosure=True)
    l1=circ.circlify(a1,target_enclosure=circ.Circle(*l0[0]),with_enclosure=True)
    l2=circ.circlify(a2,target_enclosure=circ.Circle(*l0[1]),with_enclosure=True)
    l3=circ.circlify(a3,target_enclosure=circ.Circle(*l0[2]),with_enclosure=True)
    fig, ax = plt.subplots(figsize=(6,6))
    l=l0+l1+l2+l3
    colors = [plt.cm.Dark2(i / len(l)) for i in range(len(l))]
    for j in l:
        # Circle is not subscriptable via j[0], j[1], j[2], one must use j.x, j.y, and j.r.
        c=plt.Circle((j.x,j.y),j.r, alpha=0.3,color=colors[l.index(j)-1])
        ax.add_patch(c)
    ax.plot()
    plt.show()


if __name__ == "__main__":
    drawMutliCircle()
```

If it still doesn't work, please check out how it's done in the [tests](https://github.com/elmotec/circlify/blob/4db4e005108ec56c9d378b5cd4493c32fcf715ca/circlify.py#L51).  Also note that `with_enclosure` is now `show_enclosure` in later versions.

**Comment by elmotec** [comment]
Locking this thread because it has moved quite far from the original issue.  Please open a new issue if need be.
