### ISSUE TITLE
Circles Not Populating

### ISSUE THREAD

**Issue by jkoby47** [elmotec/circlify#14]
I've tweaked the code change various sizes, not sure why my data set isn't fully printing. No errors are being flagged. Any ideas here?[
[Language Bubbles.zip](https://github.com/elmotec/circlify/files/9002437/Language.Bubbles.zip)
]

**Comment by elmotec** [comment]
Hi @jkoby47 , can you try the `children_field` attribute?

```
circles = circ.circlify(data, children_field='MSV')
```

**Comment by elmotec** [comment]
Closing, I think it should work and did not hear back.
