### ISSUE TITLE
With some data the number of generated circles is not as expected.

### ISSUE THREAD

**Issue by l-schulte** [elmotec/circlify#2]
First of all: thanks for publishing this library, it has already been of great help for the project I am working on!

The problem I am currently facing is that for some reason with specific input data the number of generated circles is just wrong.

Here two examples:
(`import circlify as c`)

`c.circlify([0.998997995991984, 0.000501002004008016, 0.000501002004008016])`
gives me the result
`[Circle(x=0.02190377678049788, y=0.0, r=0.9780962232195022), Circle(x=-0.9780962232195022, y=0.0, r=0.02190377678049785)]`
where I would have expected 3 circles.

`c.circlify([131, 91, 71, 25, 25])`
gives me the result
`[Circle(x=0.45458330153157256, y=0.0, r=0.5454166984684274), Circle(x=-0.5454166984684274, y=0.0, r=0.45458330153157256)]`
where I would have expected 5 circles.

I tested this with version 0.9.1 and 0.9.2 on Windows 10 with Python 3.7.3 as well as with version 0.9.2 on Ubuntu 16.04.6 LTS (WSL) with Python 3.5.2.

I noticed this because I am generating quite a lot of circles. I can only guess that there are more cases in which the composition of input data causes this problem.

**Comment by elmotec** [comment]
Thank you very much for the bug report. I think the issue is fixed in 0.9.3. The mention of the issue in the commit message closed the issue automatically. Feel free to re-open it or open a different one if it does not work for you. Thanks again.
