### ISSUE TITLE
Labelling with circ.bubbles doesnot match the circles

### ISSUE THREAD

**Issue by vishrutsolanki** [elmotec/circlify#4]
Hey!
So I have been trying to get used to the package and using the same code as you have in the examples I am trying to generate same visualisation. The code is as follows

data = [
        0.05, {'id': 'a2', 'datum': 0.05},
        {'id': 'a0', 'datum': 0.8, 'children': [0.3, 0.2, 0.2, 0.1], },
        {'id': 'a1', 'datum': 0.1, 'children': [
            {'id': 'a1_1', 'datum': 0.05}, {'datum': 0.04}, 0.01],
        },
    ]
circles = circ.circlify(data, show_enclosure=True)
labels = [0.05,0.05,0.8,0.3, 0.2, 0.2, 0.1,0.1,0.05,0.04,0.01]
circ.bubbles(circles,labels)

However I get the following image with improper labelling. 
![image](https://user-images.githubusercontent.com/44982942/85061501-32e8e500-b1a7-11ea-8281-7571e6b5dabc.png)

I have followed the same sequence of labelling as they appear in the data input command. Am I doing something wrong with the labels list?

Thanks!!

**Comment by elmotec** [comment]
Thank you for taking the time to create this issue. 

I suspect `circlify.bubbles` is not quite working the way you expect. The order of the circles in `circles` does not match the order in `data`. You can see it with the following code that number the circles in the order in which they are drawn:
```
labels = range(len(circles))
circ.bubbles(circles, labels)
```
Having said that, I recognize that it's not really intuitive and I will be making some changes to default the labels to sensible values based on the data.

**Comment by elmotec** [comment]
Hopefully [v0.11.0](https://pypi.org/project/circlify/) will help clear the confusion. Information related to the input data is now carried in the `Circle` data structure when the input is scalar. The `labels` parameter in `bubbles` is now optional.
```
circ.bubbles(circles)
```
should give you what you want.
