### ISSUE TITLE
circlify.bubbles typo

### ISSUE THREAD

**Issue by jgrooviest** [elmotec/circlify#6]
Line 48: `pltp.Circle` should read `plt.Circle`. This error results in matplotlib only plotting the labels rather than the circles.

**Comment by elmotec** [comment]
Thank you @jgrooviest. I could see the circle with matplotlib.patches (pltp) in my configuration (Windows) but I removed the references to pltp in 1c752993b because it does not seem to be necessary anymore: `plt.Circle` works for me as well with the latest matplotlib as you pointed out.

**Comment by jgrooviest** [comment]
@elmotec my apologies. I didn't catch that import of matplotlib.patches, and once it worked with just pyplot stopped searching for the issue.

**Comment by elmotec** [comment]
No worry. It allowed me to get rid of patches and simplify.
