### ISSUE TITLE
Recommendation and issue 

### ISSUE THREAD

**Issue by dreammirror000** [elmotec/circlify#8]
First, let me thank you for this code. However, I have some questions and recommendation.
I would recommend to emphasize the description of the input, indeed it's area and not radius as some (me included) may think.
Moreover, an option to scale or not would be cool.

I tried to use the library but had weird results, maybe you could explain them:

```
from pprint import pprint as pp
import circlify as circ
import matplotlib  
import math
pi=math.pi
data= [{'id': '2.4',     'datum': pi*2.4**2}]*1     + \
      [{'id': '1.825',   'datum': pi*1.825**2}]*1   +  \
      [{'id': '1.55',    'datum': pi*1.55**2}]*6    + \
      [{'id': '1.275',   'datum': pi*1.275**2}]*8   + \
      [{'id': '1.1875',  'datum': pi*1.1875**2}]*9
 circles = circ.circlify(data, show_enclosure=True)
pp(circles)
circ.bubbles(circles)
```

That gives the following figure, which is clearly not optimized. 
Is it a limit of the algo or an issue in the code?
Best regards.

![Figure 2021-02-01 154040](https://user-images.githubusercontent.com/78364347/106473277-e5a25500-64a3-11eb-9a56-2876eda419da.png)

**Comment by elmotec** [comment]
Thanks for the feedback. The documentation was an easy fix. The packing not so much but I manage to improve it a little. I added some of the test cases from the Huang paper (whose algorithm is not fully implemented) to get a sense of how far we are and though it's not as bad as your screenshot anymore we are still between 10% and 25% worse. 

The screenshot below is the output with the new algorithm. I will release an update today.

![Figure_1](https://user-images.githubusercontent.com/1107551/107122885-7c865d00-6868-11eb-9ebb-36670dff6576.png)

**Comment by elmotec** [comment]
Closing with release [v0.13](https://pypi.org/project/circlify/)

**Comment by dreammirror000** [comment]
Thank you again for your work. 
This code may be mainly used for infographics, however, its potentiel application in engineering is huge, among then, the conception of electrical harness. Keep up the work. I would gladly share other recommandation if you want.

**Comment by elmotec** [comment]
Thanks. To be honest, I have not been able to reproduce exactly the A1.5 algorithm and I settled for a heuristic that gives decent enough results (at least [83% of the density results in the paper](https://github.com/elmotec/circlify/blob/30e21a8a1facfa3f579a922dcc78add23adac09a/tests.py#L158)) relatively quickly. The cost of the configuration to be minimized is [the sum of the distance to the other circles weighted by the radius of that other circle](https://github.com/elmotec/circlify/blob/30e21a8a1facfa3f579a922dcc78add23adac09a/circlify.py#L232) so we try to place smaller circles close to the big ones. I imagine that for design purposes a more expensive approach based on combinatorial problems theory would give better results but much more slowly.

It's just a hobby and I don't have too much time for it but feel free to send feedback or PRs.
